mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text

polls/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.http import Http404
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from TwitterAPI import TwitterAPI


from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    tweets = None
    if(request.GET.get('mybtn')=="Click"):
    	tweets = tweet(request.GET.get('twitterHandle'));
    elif(request.GET.get('mybtn')=="Tweet"):
    	updateStatus(request.GET.get('twitterHandle'));

    context = {'latest_question_list': latest_question_list, 'tweets' : tweets}
    return render(request, 'polls/index.html', context)
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

def tweet(twitterHandle):
	api = getAPI()
	public_tweets = api.request('users/show', {'screen_name':twitterHandle, 'count':200})
	return public_tweets;

def updateStatus(tweet):
	api = getAPI()
	status = api.request('statuses/update', {'status':tweet})
	print(status.status_code)

def getAPI():
    #consumer, consec, key, sec
    api = TwitterAPI("consumer", "consumer_secret","key", "key_secret")
	
    return api

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<br>
<br>

<h1>Tweets</h1>
<form action="/polls/" method="get">
	<input type="text" name="twitterHandle" />
	<input type="submit" value="Click" name="mybtn"/>
    <input type="submit" value="Tweet" name="mybtn"/>
</form>
{% if tweets %}
	<ul>
    {% for tweet in tweets %}
        <li>{{ tweet.status.text }}</li>
    {% endfor %}
    </ul>

{% endif %}